Menu homologado
CONABIO/paisMaravillas pull request #17
Opened 2023-04-17 23:35 UTC by conaaxo

2023-05-03 07:24 UTC, albertoglezba requested changes
Hay varios archivos que no es necesario subirlos (imágenes, js, READMES, etc), podrías borrarlos.
Posteriormente atender los comentarios acerca de duplicación de inserciones de plugins.
Atender las peticiones de cambio de ser posible, y
ya con una lista más pequeña de archivos cambiados que se tenga la certeza que sí se tienen que subir, podríamos ver uno a uno como sustituir ciertas reglas de css.

2023-05-03 07:24 UTC, albertoglezba commented on assets/img/conoce/vecinosverde/bottom.png
Es preferible establecer fondo con CSS en vez de con imagen

2023-05-03 07:24 UTC, albertoglezba commented on arboles.html
> +          rel="stylesheet">
En un futuro no muy lejano hay que revisar cual de todas estas fuentes se utilizan y cuales no...
Considero que sí son pocos los iconos que se utilizan de fontAwesome, sería conveniente mejor bajarlos de fontello ya que el tamaño de la fuente, js y css disminuye bastante

2023-05-03 07:24 UTC, albertoglezba commented on assets/img/actividades/colorear/patronC.png
También este patrón puede ser generado con CSS

2023-05-03 07:24 UTC, albertoglezba commented on assets/mega-site-navigation/css/style.css
> +  /*min-height: 100vh;*/
como aún no contamos con un minificador en producción, lo mejor es no subir al PR lineas de código comentado

2023-05-03 07:24 UTC, albertoglezba commented on cantos.html
Borrar código comentado

2023-05-03 07:24 UTC, albertoglezba commented on carteles.html
> +                                        <br>
Usar CSS para dar márgenes, en este caso las clases auxiliares de bootstrap quedaría mejor

2023-05-03 07:24 UTC, albertoglezba commented on css/color.css
> +  bottom: 0;
En pantallas pequeñaas o tabletas apaisadas  no se aprecian bien los iconos de las demás actividades para colorear, sugiero que el footer no sea fixed, y en todo caso usas las clases auxiliares de bootstrap para tal efecto

2023-05-03 07:24 UTC, albertoglezba commented on color_golfo.html
>      <script src="js/waypoints.min.js"></script>
¿Se utilizan aquí estos plugins?

2023-05-03 07:24 UTC, albertoglezba commented on color_matorral.html
> +<!--scripts fuera del template base, tomé los del morphing modals, pero podrían ser en una carpeta afuera-->
Tenía entendido wow.js se ocupa solo en el index ¿es correcto?

2023-05-03 07:24 UTC, albertoglezba commented on color_pacifico.html
mismas recomendaciones que los anteriores de los archivos de colorear

2023-05-03 07:24 UTC, albertoglezba commented on color_pastizal.html
mismas recomendaciones que los anteriores de los archivos de colorear

2023-05-03 07:24 UTC, albertoglezba commented on color_selvah.html
mismas recomendaciones que los anteriores de los archivos de colorear

2023-05-03 07:24 UTC, albertoglezba commented on colorear.html
> +        <!--banderín BIO-->
evitar subir código comentado

2023-05-03 07:24 UTC, albertoglezba commented on colorear.html
> +    <script src="js/jquery-2.2.4.min.js"></script>
jquery duplicado, ya hay una versión 2.1x abajo

2023-05-03 07:24 UTC, albertoglezba commented on colorear.html
> +<script src="assets/morphing-modal/js/jquery-2.1.1.js"></script> <!-- jquery -->
Esta versión de jQuery es la que se tendría que eliminar

2023-05-03 07:24 UTC, albertoglezba commented on css/ahorcado.css
> +  bottom: 0;
Misma recomendación que en la sección de colorear, para evitar reglas de css duplicadas, utilizar clases de bootstrap (o evitar que el footer quede fijo)

2023-05-03 07:24 UTC, albertoglezba commented on css/cuidas.css
> +      font-size: 20px;
para tamaños de fuente en distintos dispositivos quizá convenga más usar `rem` en vez de `px`

2023-05-03 07:24 UTC, albertoglezba commented on css/cuidas_tablet.css
¿Es necesario este archivo para tabletas? 
¿Se podría realizar con marcado de Bootstrap?

2023-05-03 07:24 UTC, albertoglezba commented on css/lagranfamilia.css
> +
¿El modal de bootstrap no se ve adecuado?

2023-05-03 07:24 UTC, albertoglezba commented on css/memorama.css
> +  bottom: 0;
Igual que las anteriores

2023-05-03 07:24 UTC, albertoglezba commented on css/rompecabezas.css
> +  bottom: 0;
IDEM

2023-05-03 07:24 UTC, albertoglezba commented on css/style.css
> +	margin: 0px 0px 0px 0px;
usar clases auxiliares de bootstrap

2023-05-03 07:24 UTC, albertoglezba commented on css/style.css
> +}
Veo que el espaciados 75 es el más utilizado, ¿podríamos revisar estas reglas a ver cual se puede omitir?

2023-05-03 07:24 UTC, albertoglezba commented on css/style.css
> +}
Utilizar clases auxiliares de Bootstrap

2023-05-03 07:24 UTC, albertoglezba commented on css/style_tablet.css
Idealmente  habría que borrar este archivo y que el sitio sea responsivo, de no poderse, estos cambios se aplicar usando por las clases auxiliares de Bootstrap

2023-05-03 07:24 UTC, albertoglezba commented on css/styles.css
>    opacity: 0.5;
Borrar código comentado

2023-05-03 07:24 UTC, albertoglezba commented on css/styles.css
Hay que revisar estas reglas, dudo que se utilicen las +6000 lineas de estilos (en todo caso, seccionarlas para archivos específicos).
Esto es un detalle que se viene arrastrando de versiones anteriores... podemos dejarlo para el mediano plazo.

2023-05-03 07:24 UTC, albertoglezba commented on css/vecinos.css
Procura no utilizar tu nombre en las clases que se utilizan

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/animated-headline/README.md
Archivo no necesario

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/animated-headline/css/reset.css
Es parte de un plugin, ¿es necesario? ¿no se puede realizar con lo ya existente?
La idea es aligerar el sitio, no engrosarlo más

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/animated-headline/css/style.css
Es parte de un plugin, ¿es necesario? ¿no se puede realizar con lo ya existente?
La idea es aligerar el sitio, no engrosarlo más

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/animated-headline/index.html
Archivo de ejemplo no es necesario añadirlo como commit para subir al repo o a producción

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/animated-headline/js/jquery-2.1.1.js
¿Es un jQuery modificado? ¿no se puede usar la versión que ya esta arriba? (En todo caso de no ser necesario el plugin, la biblioteca tampoco lo sería aquí)

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/animated-headline/js/main.js
Mismo comentario que arriba

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/animated-headline/js/modernizr.js
Acabo de darme cuenta que todo esto también se encuentra en raíz, mejor agarrarlo de ahí (sí es necesario)

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/animated-headline/partials/_layout.scss
Acabo de darme cuenta que todo esto también se encuentra en raíz, mejor agarrarlo de ahí (sí es necesario)

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/animated-headline/partials/_mixins.scss
Acabo de darme cuenta que todo esto también se encuentra en raíz, mejor agarrarlo de ahí (sí es necesario)

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/animated-headline/partials/_variables.scss
Acabo de darme cuenta que todo esto también se encuentra en raíz, mejor agarrarlo de ahí (sí es necesario)

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/animated-headline/scss/style.scss
Acabo de darme cuenta que todo esto también se encuentra en raíz, mejor agarrarlo de ahí (sí es necesario)

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/img/home/home/00.png
Este archivo no se ocupa dentro de invasoras

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/img/home/home/000.png
Este archivo no se ocupa dentro de invasoras aparte de ser una imagen vacía

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/img/home/home/03.jpg
No encuentro referencia a esta imagen dentro de la carpeta de invasoras

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/img/home/home/04.jpg
No encuentro referencia a esta imagen dentro de la carpeta de invasoras

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/img/home/home/12.jpg
No encuentro referencia a esta imagen dentro de la carpeta de invasoras

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/img/home/home/14.jpg
No encuentro referencia a esta imagen dentro de la carpeta de invasoras

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/img/home/home/21.jpg
No encuentro referencia a esta imagen dentro de la carpeta de invasoras

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/img/home/home/22.jpg
No encuentro referencia a esta imagen dentro de la carpeta de invasoras

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/img/home/home/23.jpg
No encuentro referencia a esta imagen dentro de la carpeta de invasoras

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/img/home/home/26.jpg
No encuentro referencia a esta imagen dentro de la carpeta de invasoras

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/img/home/home/CONABIO-logo2021-01.svg
No encuentro referencia a esta imagen dentro de la carpeta de invasoras

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/img/home/home/abajo.png
No encuentro referencia a esta imagen dentro de la carpeta de invasoras

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/img/home/home/guiamaestros.jpg
No encuentro referencia a esta imagen dentro de la carpeta de invasoras

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/img/home/home/guiamaestros_0.jpg
No encuentro referencia a esta imagen dentro de la carpeta de invasoras

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/img/home/home/logo-mexico-blanco.png
No encuentro referencia a esta imagen dentro de la carpeta de invasoras

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/img/home/home/logo58_conabio.png
No encuentro referencia a esta imagen dentro de la carpeta de invasoras

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/img/home/home/logo64_conabio.png
No encuentro referencia a esta imagen dentro de la carpeta de invasoras

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/img/home/home/logo_logob_gobmx.png
No encuentro referencia a esta imagen dentro de la carpeta de invasoras

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/img/home/CONABIO-logo2021-01.svg
Este archivo no se ocupa dentro de invasoras

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/img/home/home/logotipohome.png
Este archivo no se utiliza dentro de invasoras.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/img/home/home/m_enlace.png
No encuentro referencia a esta imagen dentro de la carpeta de invasoras

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/img/home/home/maestros.png
No encuentro referencia a esta imagen dentro de la carpeta de invasoras

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/img/home/home/premio.png
No encuentro referencia a esta imagen dentro de la carpeta de invasoras

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/img/home/home/premio2.jpg
No encuentro referencia a esta imagen dentro de la carpeta de invasoras

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/img/home/home/premiounete.png
No encuentro referencia a esta imagen dentro de la carpeta de invasoras

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/img/home/home/programa.jpg
No encuentro referencia a esta imagen dentro de la carpeta de invasoras

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/img/home/home/tito.png
No encuentro referencia a esta imagen dentro de la carpeta de invasoras

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/img/home/home/titohome_1.png
No encuentro referencia a esta imagen dentro de la carpeta de invasoras

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/img/home/home/titologo.png
No encuentro referencia a esta imagen dentro de la carpeta de invasoras

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/img/home/home/titopapel.png
No encuentro referencia a esta imagen dentro de la carpeta de invasoras

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/mega-site-navigation/README.md
Este archivo no es necesario subirlo ni a producción ni al repositorio

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/mega-site-navigation/css/reset.css
Al igual que animated-headline, este plugin se encuentra en raíz, ¿Por qué es necesario duplicarlo?

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/mega-site-navigation/css/style.css
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/mega-site-navigation/img/cd-logo.svg
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/mega-site-navigation/img/img.jpg
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/mega-site-navigation/img/line-icon-1.svg
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/mega-site-navigation/img/line-icon-2.svg
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/mega-site-navigation/img/line-icon-3.svg
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/mega-site-navigation/img/line-icon-4.svg
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/mega-site-navigation/img/line-icon-5.svg
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/mega-site-navigation/img/line-icon-6.svg
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/mega-site-navigation/img/line-icon-7.svg
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/mega-site-navigation/img/line-icon-8.svg
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/mega-site-navigation/index.html
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/mega-site-navigation/js/jquery-2.1.1.js
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/mega-site-navigation/js/jquery.mobile.custom.min.js
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/mega-site-navigation/js/main.js
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/mega-site-navigation/js/modernizr.js
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/mega-site-navigation/partials/_layout.scss
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/mega-site-navigation/partials/_variables.scss
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/mega-site-navigation/scss/style.scss
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/morphing-modal/README.md
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/morphing-modal/css/reset.css
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/morphing-modal/css/style.css
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/morphing-modal/img/cd-icon-close.svg
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/morphing-modal/index.html
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/morphing-modal/js/jquery-2.1.1.js
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/morphing-modal/js/main.js
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/morphing-modal/js/modernizr.js
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/morphing-modal/js/velocity-LICENSE.md
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/morphing-modal/js/velocity.min.js
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/morphing-modal/partials/_layout.scss
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/morphing-modal/partials/_mixins.scss
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/morphing-modal/partials/_variables.scss
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/assets/morphing-modal/scss/style.scss
Al igual que animated-headline, este plugin se encuentra en raíz, no creo conveniente duplicarlo.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/capsulas.html
>  				<br><br>
Evitar espaciar con `br`

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/capsulas.html
> +                <div class="spacer100"></div>
Entiendo esos div son para crear espacios... ¿Valen la pena? con las clases auxiliares de bootstrap no funcionarían?

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/css/capsulas.css
No subir código comentado... eventualmente al igual que el resto de los css, hay que revisar que se usa, que no, y que se puede sustituir por clases auxiliares de bootstrap

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/css/invasion.css
Hay que echarle un ojo a estas reglas, ya que el archivo de invasion.html el footer se come el contenido en pantallas pequeñas (HD 1366*768)
![Captura de pantalla 2023-05-02 a la(s) 22 18 25](https://user-images.githubusercontent.com/5861322/235832274-cd6553fc-8f5a-470f-9e47-dfdf51133314.png)

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/css/style.css
> +
en efecto, revisar

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/css/style_tablet.css
Igual que los archivos anteriores de tableta, tratar de que quede con la responsividad de la biblioteca

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/invasion.html
> +    <script src="js/all.js"></script>
¿todo esto es necesario?

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/js/jquery-2.2.4.min.js
¿Por qué se volvió a subir este archivo?

2023-05-03 07:24 UTC, albertoglezba commented on js/encuentra.js
¿Qué fue lo que cambió?

2023-05-03 07:24 UTC, albertoglezba commented on js/jquery-3.6.4.min.js
¿Por qué se volvió a subir este archivo?

2023-05-03 07:24 UTC, albertoglezba commented on js/memorama.js
¿Qué cambio aquí?

2023-05-03 07:24 UTC, albertoglezba commented on lagranfamilia.html
> +<div class="spacer150 colorlagranfamilia"></div>
Revisar espaciadores, utilizar clases de bootstrap

2023-05-03 07:24 UTC, albertoglezba commented on mem_bosquet.html
> +<div class="spacer75"></div>
idem

2023-05-03 07:24 UTC, albertoglezba commented on mem_campo.html
> +<div class="spacer75"></div>
idem

2023-05-03 07:24 UTC, albertoglezba commented on mem_campo.html
> +<script src="assets/mega-site-navigation/js/main.js"></script> <!-- mega menu -->
¡Esta duplicado este script, ya se esta agregando al momento de pegar el menú!
Agrego la lista de archivos donde potencialmente se tiene duplicidad:

![Captura de pantalla 2023-05-02 a la(s) 22 52 48](https://user-images.githubusercontent.com/5861322/235835156-ae6f81c1-80d7-4212-8c4f-fff253918fb0.png)

2023-05-03 07:24 UTC, albertoglezba commented on arboles.html
> +<script src="assets/mega-site-navigation/js/main.js"></script> <!-- mega menu -->
Plugin ya se esta insertando arriba en la inserción del menú

2023-05-03 07:24 UTC, albertoglezba commented on rom_golfo.html
> +<script src="assets/mega-site-navigation/js/main.js"></script> <!-- mega menu -->
Plugin ya se esta insertando arriba en la inserción del menú

2023-05-03 07:24 UTC, albertoglezba commented on rom_golfo.html
> +<div class="spacer75"></div>
Checar espaciadores

2023-05-03 07:24 UTC, albertoglezba commented on color_bosquet.html
> +<script src="assets/mega-site-navigation/js/main.js"></script> <!-- mega menu -->
Plugin ya se esta insertando arriba en la inserción del menú

2023-05-03 07:24 UTC, albertoglezba commented on color_golfo.html
> +<script src="assets/mega-site-navigation/js/main.js"></script> <!-- mega menu -->
Plugin ya se esta insertando arriba en la inserción del menú

2023-05-03 07:24 UTC, albertoglezba commented on color_matorral.html
> +<script src="assets/mega-site-navigation/js/main.js"></script> <!-- mega menu -->
Plugin ya se esta insertando arriba en la inserción del menú

2023-05-03 07:24 UTC, albertoglezba commented on color_pacifico.html
> +<script src="assets/mega-site-navigation/js/main.js"></script> <!-- mega menu -->
Plugin ya se esta insertando arriba en la inserción del menú

2023-05-03 07:24 UTC, albertoglezba commented on color_pastizal.html
> +<script src="assets/mega-site-navigation/js/main.js"></script> <!-- mega menu -->
Plugin ya se esta insertando arriba en la inserción del menú

2023-05-03 07:24 UTC, albertoglezba commented on color_selvah.html
> +<script src="assets/mega-site-navigation/js/main.js"></script> <!-- mega menu -->
Plugin ya se esta insertando arriba en la inserción del menú

2023-05-03 07:24 UTC, albertoglezba commented on colorear.html
> +<script src="assets/mega-site-navigation/js/main.js"></script> <!-- mega menu -->
Plugin ya se esta insertando arriba en la inserción del menú

2023-05-03 07:24 UTC, albertoglezba commented on encuentra.html
> +<script src="assets/mega-site-navigation/js/main.js"></script> <!-- mega menu -->
Plugin ya se esta insertando arriba en la inserción del menú

2023-05-03 07:24 UTC, albertoglezba commented on megadiverso.html
> +<script src="assets/mega-site-navigation/js/main.js"></script> <!-- mega menu -->
Plugin ya se esta insertando arriba en la inserción del menú

2023-05-03 07:24 UTC, albertoglezba commented on mem_bosquet.html
> +<script src="assets/mega-site-navigation/js/main.js"></script> <!-- mega menu -->
Plugin ya se esta insertando arriba en la inserción del menú

2023-05-03 07:24 UTC, albertoglezba commented on mem_ciudad.html
> +<script src="assets/mega-site-navigation/js/main.js"></script> <!-- mega menu -->
Plugin ya se esta insertando arriba en la inserción del menú

2023-05-03 07:24 UTC, albertoglezba commented on mem_golfo.html
> +<script src="assets/mega-site-navigation/js/main.js"></script> <!-- mega menu -->
Plugin ya se esta insertando arriba en la inserción del menú

2023-05-03 07:24 UTC, albertoglezba commented on mem_golfo.html
> +<div class="spacer75"></div>
revisar espaciadores

2023-05-03 07:24 UTC, albertoglezba commented on mem_matorral.html
> +<script src="assets/mega-site-navigation/js/main.js"></script> <!-- mega menu -->
Plugin ya se esta insertando arriba en la inserción del menú

2023-05-03 07:24 UTC, albertoglezba commented on mem_pacifico.html
> +<div class="spacer75"></div>
revisar espaciadores

2023-05-03 07:24 UTC, albertoglezba commented on mem_pacifico.html
> +<script src="assets/mega-site-navigation/js/main.js"></script> <!-- mega menu -->
Plugin ya se esta insertando arriba en la inserción del menú

2023-05-03 07:24 UTC, albertoglezba commented on mem_pastizal.html
> +<script src="assets/mega-site-navigation/js/main.js"></script> <!-- mega menu -->
Plugin ya se esta insertando arriba en la inserción del menú

2023-05-03 07:24 UTC, albertoglezba commented on mem_selvah.html
> +<script src="assets/mega-site-navigation/js/main.js"></script> <!-- mega menu -->
Plugin ya se esta insertando arriba en la inserción del menú

2023-05-03 07:24 UTC, albertoglezba commented on memoramas.html
> +<script src="assets/mega-site-navigation/js/main.js"></script> <!-- mega menu -->
Plugin ya se esta insertando arriba en la inserción del menú

2023-05-03 07:24 UTC, albertoglezba commented on obtenemos.html
> +    <title>¿Qué obtenemos? | el país de las maravillas</title>
"el" con "E" mayúscula

2023-05-03 07:24 UTC, albertoglezba commented on publicaciones.html
> +    <title>Publicaciones | el país de las maravillas</title>
"el" con "E" mayúscula

2023-05-03 07:24 UTC, albertoglezba commented on quedana.html
> +    <title>¿Cómo dañamos los ecosistemas? | el país de las maravillas</title>
"el" con "E" mayúscula

2023-05-03 07:24 UTC, albertoglezba commented on quepasa.html
> +    <title>¿Qué pasa cuando eliminamos? | el país de las maravillas</title>
"el" con "E" mayúscula

2023-05-03 07:24 UTC, albertoglezba commented on recortables.html
> +    <title>Recortables | el país de las maravillas</title>
"el" con "E" mayúscula

2023-05-03 07:24 UTC, albertoglezba commented on rom_bosquet.html
> +<script src="assets/mega-site-navigation/js/main.js"></script> <!-- mega menu -->
Plugin ya se esta insertando arriba en la inserción del menú

2023-05-03 07:24 UTC, albertoglezba commented on rom_campo.html
> +<script src="assets/mega-site-navigation/js/main.js"></script> <!-- mega menu -->
Plugin ya se esta insertando arriba en la inserción del menú

2023-05-03 07:24 UTC, albertoglezba commented on rom_ciudad.html
> +<script src="assets/mega-site-navigation/js/main.js"></script> <!-- mega menu -->
Plugin ya se esta insertando arriba en la inserción del menú

2023-05-03 07:24 UTC, albertoglezba commented on rom_matorral.html
> +<script src="assets/mega-site-navigation/js/main.js"></script> <!-- mega menu -->
Plugin ya se esta insertando arriba en la inserción del menú

2023-05-03 07:24 UTC, albertoglezba commented on rom_pacifico.html
> +<script src="assets/mega-site-navigation/js/main.js"></script> <!-- mega menu -->
Plugin ya se esta insertando arriba en la inserción del menú

2023-05-03 07:24 UTC, albertoglezba commented on rom_pastizal.html
> +<script src="assets/mega-site-navigation/js/main.js"></script> <!-- mega menu -->
Plugin ya se esta insertando arriba en la inserción del menú

2023-05-03 07:24 UTC, albertoglezba commented on rom_selvah.html
> +<script src="assets/mega-site-navigation/js/main.js"></script> <!-- mega menu -->
Plugin ya se esta insertando arriba en la inserción del menú

2023-05-03 07:24 UTC, albertoglezba commented on rompecabezas.html
> +<script src="assets/mega-site-navigation/js/main.js"></script> <!-- mega menu -->
Plugin ya se esta insertando arriba en la inserción del menú

2023-05-03 07:24 UTC, albertoglezba commented on sitiosweb.html
> +    <title>Sitios web | el país de las maravillas</title>
"el" con "E" mayúscula

2023-05-03 07:24 UTC, albertoglezba commented on vecinos.html
> +    <title>Vecinos verdes | el país de las maravillas</title>
"el" con "E" mayúscula

2023-05-03 07:24 UTC, albertoglezba commented on vecinos.html
> +    </section>
Evitar clases o ids personalizados, preferible que sean autoexplicativos.
Dicha imagen es un cuadro gris vacío, se puede sustituir con reglas css, o en su defecto, quitarse.

2023-05-03 07:24 UTC, albertoglezba commented on invasoras/js/jquery-2.2.4.min.js
¿Por qué se volvió a subir esta biblioteca?

2023-05-03 18:09 UTC, conaaxo commented on assets/img/conoce/vecinosverde/bottom.png
listo

2023-05-03 18:37 UTC, conaaxo commented on arboles.html
> +          rel="stylesheet">
Se considera para la siguiente versión

2023-05-03 18:37 UTC, conaaxo commented on assets/mega-site-navigation/css/style.css
> +  /*min-height: 100vh;*/
ok, reduzco mis comentarios,

2023-05-03 18:37 UTC, conaaxo commented on carteles.html
> +                                        <br>
claro

2023-05-03 18:38 UTC, conaaxo commented on css/color.css
> +  bottom: 0;
se trabaja la adaptabilidad para todas las actividades en la siguiente versión

2023-05-03 18:41 UTC, conaaxo commented on color_golfo.html
>      <script src="js/waypoints.min.js"></script>
ya lo probé en las secciones de colorear y no veo falla, los quito

2023-05-03 18:45 UTC, conaaxo commented on color_matorral.html
> +<!--scripts fuera del template base, tomé los del morphing modals, pero podrían ser en una carpeta afuera-->
Ya lo eliminé de algunas secciones y no veo errores, lo voy removiendo

2023-05-04 15:26 UTC, conaaxo commented on arboles.html
> +          rel="stylesheet">
fontawesome.com lo dejo solo en las páginas necesarias por el momento

2023-05-04 15:34 UTC, conaaxo commented on rompecabezas.html
> +<script src="assets/mega-site-navigation/js/main.js"></script> <!-- mega menu -->
ok, se elimina de los que sea necesario

2023-05-04 17:47 UTC, conaaxo commented on carteles.html
> +                                        <br>
era prueba, pero se solucionó con CSS

2023-05-04 17:48 UTC, conaaxo commented on css/ahorcado.css
> +  bottom: 0;
se trabaja menú y nuevo  footer para las actividades de la siguiente versión

2023-05-04 17:49 UTC, conaaxo commented on css/cuidas_tablet.css
ya se eliminan varios tablet css innecesarios

2023-05-04 17:51 UTC, conaaxo commented on css/lagranfamilia.css
> +
se adecuan medias @media only screen and (max-width: 1199px) and (min-width: 601px){

y se reduce codigo

2023-05-04 19:07 UTC, conaaxo commented on css/styles.css
>    opacity: 0.5;
elimino comentarios

2023-05-04 19:08 UTC, conaaxo commented on css/vecinos.css
los AXO los uso justo para pruebas, ya se eliminan los resagados

2023-05-04 23:44 UTC, conaaxo commented on invasoras/assets/animated-headline/css/reset.css
simplificando invasoras

2023-05-04 23:45 UTC, conaaxo commented on invasoras/assets/animated-headline/js/modernizr.js
se fué

2023-05-08 22:41 UTC, conaaxo commented on assets/img/actividades/colorear/patronC.png
ok

2023-05-08 23:30 UTC, conaaxo commented on assets/img/actividades/colorear/patronC.png
Listo

2023-10-02 22:41 UTC, merged